export default {
  ['zh-CN']: {
    '_settings': {
      rootWidth: '350px',
      numberInputMinWidth: '42px',
      controlWidth: '215px',
    },
    'ui.subtitle': '基于WebGL2的液态玻璃效果模拟工具',
    'editor.basicSettings': '基础设置',
    'editor.language': '语言',
    'editor.refThickness': '折射厚度',
    'editor.refFactor': '折射系数',
    'editor.refDispersion': '色散增益',
    'editor.refFresnelRange': '菲涅尔反射范围',
    'editor.refFresnelHardness': '菲涅尔反射硬度',
    'editor.refFresnelFactor': '菲涅尔反射强度',
    'editor.glareRange': '高光范围',
    'editor.glareHardness': '高光硬度',
    'editor.glareConvergence': '高光聚拢度',
    'editor.glareOppositeFactor': '高光对侧强度',
    'editor.glareFactor': '高光强度',
    'editor.glareAngle': '高光角度',
    'editor.blurRadius': '模糊半径',
    'editor.blurEdge': '模糊边缘',
    'editor.tint': '色调',
    'editor.shadowExpand': '阴影扩散',
    'editor.shadowFactor': '阴影强度',
    'editor.shadowPosition': '阴影位置',
    'editor.bgType': '背景',
    'editor.shapeSettings': '形状设置',
    'editor.shapeWidth': '宽',
    'editor.shapeHeight': '高',
    'editor.shapeRadius': '圆角 (%)',
    'editor.shapeRoundness': '超椭圆系数',
    'editor.mergeRate': '形状融合度',
    'editor.showShape1': '显示第二个图形',
    'editor.animationSettings': '动画设置',
    'editor.springSizeFactor': '动画形变',
    'editor.debugSettings': '调试',
    'editor.export': '导出预设',
    'editor.import': '导入预设',
    'editor.importSuccessMessage': '预设导入成功！',
    'editor.importFailedMessage': (message: string) => `导入失败：${message}`,
    'editor.backgroundOpacity': '背景透明度',
    'editor.blurAmount': '模糊量',
    'editor.borderOpacity': '边框透明度',
    'editor.borderRadius': '边框圆角',
    'editor.shadowIntensity': '阴影强度',
    'editor.focusBorderColor': '焦点边框颜色',
  },
  ['en-US']: {
    '_settings': {
      rootWidth: '400px',
      numberInputMinWidth: '42px',
      controlWidth: '215px',
    },
    'ui.subtitle': 'Liquid Glass Effect Simulation Tool based on WebGL2',
    'editor.basicSettings': 'Basic Settings',
    'editor.language': 'Language',
    'editor.refThickness': 'Thickness',
    'editor.refFactor': 'Refraction Factor',
    'editor.refDispersion': 'Dispersion Gain',
    'editor.refFresnelRange': 'Fresnel Size',
    'editor.refFresnelHardness': 'Fresnel Hardness',
    'editor.refFresnelFactor': 'Fresnel Intensity',
    'editor.glareRange': 'Glare Size',
    'editor.glareHardness': 'Glare Hardness',
    'editor.glareConvergence': 'Glare Convergence',
    'editor.glareOppositeFactor': 'Glare Opposite Side',
    'editor.glareFactor': 'Glare Intensity',
    'editor.glareAngle': 'Glare Angle',
    'editor.blurRadius': 'Blur Radius',
    'editor.blurEdge': 'Blur Edge',
    'editor.tint': 'Tint',
    'editor.shadowExpand': 'Shadow Expand',
    'editor.shadowFactor': 'Shadow Intensity',
    'editor.shadowPosition': 'Shadow Position',
    'editor.bgType': 'Background',
    'editor.shapeSettings': 'Shape Settings',
    'editor.shapeWidth': 'Width',
    'editor.shapeHeight': 'Height',
    'editor.shapeRadius': 'Radius (%)',
    'editor.shapeRoundness': 'SuperEllipse Factor',
    'editor.mergeRate': 'Merge Rate',
    'editor.showShape1': 'Show 2nd Shape',
    'editor.animationSettings': 'Animation Settings',
    'editor.springSizeFactor': 'Animation Morph',
    'editor.debugSettings': 'Debug',
    'editor.export': 'Export Preset',
    'editor.import': 'Import Preset',
    'editor.importSuccessMessage': 'Preset imported successfully!',
    'editor.importFailedMessage': (message: string) => `Import failed: ${message}`,
    'editor.backgroundOpacity': 'Background Opacity',
    'editor.blurAmount': 'Blur Amount',
    'editor.borderOpacity': 'Border Opacity',
    'editor.borderRadius': 'Border Radius',
    'editor.shadowIntensity': 'Shadow Intensity',
    'editor.focusBorderColor': 'Focus Border Color',
  },
  ['uz-UZ']: {
    '_settings': {
      "rootWidth": "400px",
      "numberInputMinWidth": "42px",
      "controlWidth": "215px"
    },
    "ui.subtitle": "WebGL2 asosidagi Liquid Glass effekt simulyatori",
    "editor.basicSettings": "Asosiy sozlamalar",
    "editor.language": "Til",
    "editor.refThickness": "Qalinlik",
    "editor.refFactor": "Sinish koeffitsiyenti",
    "editor.refDispersion": "Dispersiya darajasi",
    "editor.refFresnelRange": "Fresnel o‘lchami",
    "editor.refFresnelHardness": "Fresnel qattiqligi",
    "editor.refFresnelFactor": "Fresnel intensivligi",
    "editor.glareRange": "Yaltiroq maydoni",
    "editor.glareHardness": "Yaltiroq qattiqligi",
    "editor.glareConvergence": "Yaltiroq to‘planishi",
    "editor.glareOppositeFactor": "Qarama-qarshi tomon yorqinligi",
    "editor.glareFactor": "Yaltiroq intensivligi",
    "editor.glareAngle": "Yaltiroq burchagi",
    "editor.blurRadius": "Xiralashish radiusi",
    "editor.blurEdge": "Xiralashish qirralar",
    "editor.tint": "Rang ohangi",
    "editor.shadowExpand": "Soya kengligi",
    "editor.shadowFactor": "Soya kuchi",
    "editor.shadowPosition": "Soya joylashuvi",
    "editor.bgType": "Fon turi",
    "editor.shapeSettings": "Shakl sozlamalari",
    "editor.shapeWidth": "Kenglik",
    "editor.shapeHeight": "Balandlik",
    "editor.shapeRadius": "Radius (%)",
    "editor.shapeRoundness": "Burchak yumaloqligi",
    "editor.mergeRate": "Qo‘shilish tezligi",
    "editor.showShape1": "2-shaklni ko‘rsatish",
    "editor.animationSettings": "Animatsiya sozlamalari",
    "editor.springSizeFactor": "Animatsiya deformatsiyasi",
    "editor.debugSettings": "Debug",
    "editor.export": "Presetni eksport qilish",
    "editor.import": "Presetni import qilish",
    "editor.importSuccessMessage": "Preset muvaffaqiyatli import qilindi!",
    "editor.importFailedMessage": (message: string) => `Import failed: ${message}`,
    "editor.backgroundOpacity": "Fon shaffofligi",
    "editor.blurAmount": "Xiralashish miqdori",
    "editor.borderOpacity": "Chegara shaffofligi",
    "editor.borderRadius": "Chegara radiusi",
    "editor.shadowIntensity": "Soya kuchi",
    "editor.focusBorderColor": "Fokus chegarasi rangi",
  }
}
